webtalk_init -webtalk_dir C:/Users/12875/CPU_vivado/project_4_CPU_pipeline/project_4_CPU_pipeline.sim/sim_1/behav/xsim/xsim.dir/mips_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 15 23:34:25 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2d44b02d-fffd-4f2f-9308-0ec637095e3e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "26aca39c2599499e8d48b8ff57ef94a6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "199" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "300 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.23_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "7968_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3898516698 -regid "" -xml C:/Users/12875/CPU_vivado/project_4_CPU_pipeline/project_4_CPU_pipeline.sim/sim_1/behav/xsim/xsim.dir/mips_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/12875/CPU_vivado/project_4_CPU_pipeline/project_4_CPU_pipeline.sim/sim_1/behav/xsim/xsim.dir/mips_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/12875/CPU_vivado/project_4_CPU_pipeline/project_4_CPU_pipeline.sim/sim_1/behav/xsim/xsim.dir/mips_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
